const logos = {
    "vue":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue.js_Logo_2.svg/1200px-Vue.js_Logo_2.svg.png",
    "react":"https://logos-download.com/wp-content/uploads/2016/09/React_logo_logotype_emblem.png",
    "angular":"https://cdn.freebiesupply.com/logos/large/2x/angular-icon-1-logo-png-transparent.png",
    "html":"https://logos-download.com/wp-content/uploads/2017/07/HTML5_badge.png",
    "css":"https://verekia.com/_pages/css3/introduction-css3/img/css3-logo.png",
    "js":"https://www.i-programmer.info/images/stories/prof/iprogrammer/JavascriptName/JSlogo.jpg",
    "ts":"https://www.onlinemarketingtools.pro/wp-content/uploads/2018/10/TypeScript-logo.jpg",
    "node":"https://cdn.freebiesupply.com/logos/large/2x/nodejs-icon-logo-png-transparent.png",
    "mongo":"https://cms-assets.tutsplus.com/uploads/users/1116/posts/24835/preview_image/mongodb-logo.png",
    "npm":"https://www.logolynx.com/images/logolynx/7f/7fb976a537620fed310872d533cd161c.png",
    "heroku": "https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2016/04/1461122387heroku-logo.jpg",
    "terraform": "https://www.brightbox.com/images/blog/logo-terraform-symbol.svg",
    "java": "https://cdn.freebiesupply.com/logos/large/2x/java-14-logo-png-transparent.png",
    "android": "https://logodownload.org/wp-content/uploads/2015/05/android-logo-5.png",
    "aws": "https://d1.awsstatic.com/logos/aws-logo/full-color/AWS-Logo_Full-Color_500x300.e3aa5e1294717e6c708baa2d3c1e2d2fb707ae84.png",
    "sql": "https://sqlskull.com/wp-content/uploads/2019/11/sql-logo.png",
    "python": "https://logos-download.com/wp-content/uploads/2016/10/Python_logo_icon.png",
    "opencv": "https://hacklab.cz/files/images/opencv_logo.gif"
}